# Generated by Django 4.2.4 on 2023-08-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="car_name",
            field=models.CharField(default="GMC", max_length=500),
        ),
    ]
