# Generated by Django 4.2.4 on 2023-08-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vege", "0002_recipe_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="recipe_view_counts",
            field=models.IntegerField(default=1),
        ),
    ]
